# Generated by Django 5.0.2 on 2024-02-18 15:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id_deporte', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Deporte',
                'verbose_name_plural': 'Deportes',
                'db_table': 'deportes',
            },
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id_instalacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('iluminacion', models.BooleanField(default=False)),
                ('cubierta', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Instalación',
                'verbose_name_plural': 'Instalaciones',
                'db_table': 'instalaciones',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('equipacion_principal', models.CharField(max_length=100)),
                ('equipacion_suplente', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torre_crud.deporte')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipos',
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id_partido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('puntos_local', models.PositiveIntegerField(default=0)),
                ('puntos_visitante', models.PositiveIntegerField(default=0)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torre_crud.deporte')),
                ('instalacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='torre_crud.instalacion')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='torre_crud.equipo')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='torre_crud.equipo')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'db_table': 'partidos',
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id_jugador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido1', models.CharField(max_length=20)),
                ('apellido2', models.CharField(blank=True, max_length=20, null=True)),
                ('dorsal', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('peso', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('telefono', models.CharField(max_length=15)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torre_crud.equipo')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': 'jugadores',
                'unique_together': {('equipo', 'dorsal')},
            },
        ),
    ]
