# Generated by Django 5.1.2 on 2024-10-28 22:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torre_crud', '0002_remove_equipo_deporte_alter_jugador_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id_partido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('puntos_local', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('puntos_visitante', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'db_table': 'partidos',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='id_deporte',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='id_local',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='id_visitante',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='id_deporte',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='id_instalacion',
        ),
        migrations.AlterModelOptions(
            name='deportes',
            options={'managed': True, 'verbose_name': 'Deporte', 'verbose_name_plural': 'Deportes'},
        ),
        migrations.AlterModelOptions(
            name='instalaciones',
            options={'managed': True, 'verbose_name': 'Instalación', 'verbose_name_plural': 'Instalaciones'},
        ),
        migrations.RenameModel(
            old_name='Instalacion',
            new_name='Instalaciones',
        ),
        migrations.RenameModel(
            old_name='Deporte',
            new_name='Deportes',
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('equipacion_principal', models.CharField(max_length=100)),
                ('equipacion_suplente', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('id_deporte', models.ForeignKey(db_column='id_deporte', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='torre_crud.deportes')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id_jugador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido1', models.CharField(max_length=20)),
                ('apellido2', models.CharField(blank=True, max_length=20, null=True)),
                ('dorsal', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('peso', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('telefono', models.CharField(max_length=15)),
                ('id_equipo', models.ForeignKey(db_column='id_equipo', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='torre_crud.equipos')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': 'jugadores',
                'managed': True,
                'unique_together': {('id_equipo', 'dorsal')},
            },
        ),
        migrations.DeleteModel(
            name='Jugador',
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
        migrations.DeleteModel(
            name='Partido',
        ),
    ]
